# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: eventic
language: python
runtimeConfig:
  start:
    #- "python ./eventic/src/config.py"
    #- "fastapi run eventic/main.py"
    - "python3 src/eventic/app/main.py"
database:
  hostname: ${HOSTNAME}
  port: ${PORT}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  app_db_name: ${APP_DB_NAME}
  migrate:
    - alembic upgrade head 
telemetry:
  logs:
    logLevel: INFO

