"""baseline

Revision ID: 0001
Revises:
Create Date: 2026-08-05 13:23:47.426871
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eventic_head",
        sa.Column("stream", sa.Text(), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("meta_version", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column(
            "meta",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("stream", "aggregate_id"),
    )
    op.create_table(
        "eventic_intent",
        sa.Column("intent_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Text(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("queue", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("leased_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("queue <> ''", name="ck_intent_queue"),
        sa.CheckConstraint(
            "status IN ('pending','leased','dead')", name="ck_intent_status"
        ),
        sa.PrimaryKeyConstraint("intent_id"),
        sa.UniqueConstraint("subscription_id", "revision_id", name="uq_intent_sub_rev"),
    )
    op.create_index(
        "ix_intent_drain",
        "eventic_intent",
        ["queue", "status", "available_at"],
        unique=False,
    )
    op.create_table(
        "eventic_revision",
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("stream", sa.Text(), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("meta_version", sa.Integer(), nullable=False),
        sa.Column("encoding", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column(
            "meta",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(revision = 0) = (kind = 'create')", name="ck_create_at_zero"
        ),
        sa.CheckConstraint("encoding IN ('snapshot/1','delta/1')", name="ck_encoding"),
        sa.CheckConstraint("kind IN ('create','change')", name="ck_kind"),
        sa.CheckConstraint("stream <> ''", name="ck_stream_nonempty"),
        sa.CheckConstraint("revision >= 0", name="ck_revision_nonneg"),
        sa.CheckConstraint("schema_version >= 1", name="ck_schema_version"),
        sa.PrimaryKeyConstraint("revision_id"),
        sa.UniqueConstraint("stream", "aggregate_id", "revision", name="uq_revision"),
    )
    op.create_index(
        "ix_revision_sai",
        "eventic_revision",
        ["stream", "aggregate_id", "revision"],
        unique=False,
    )
    op.create_table(
        "eventic_schema",
        sa.Column("stream", sa.Text(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("stream", "schema_version"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("eventic_schema")
    op.drop_index("ix_revision_sai", table_name="eventic_revision")
    op.drop_table("eventic_revision")
    op.drop_index("ix_intent_drain", table_name="eventic_intent")
    op.drop_table("eventic_intent")
    op.drop_table("eventic_head")
    # ### end Alembic commands ###
